export {
  PORTFOLIO_ABOUT_CONTENT,
  PORTFOLIO_ABOUT_IMAGE_URL,
  PORTFOLIO_ACCESSIBILITY_LABELS,
  PORTFOLIO_BRAND,
  PORTFOLIO_CONTACT_CONTENT,
  PORTFOLIO_LANDING_PAGE_CONTENT,
  PORTFOLIO_NAV_CONTENT,
  PORTFOLIO_PROJECTS_CONTENT,
  PORTFOLIO_SKILLS_CONTENT,
} from './portfolioContent'
